[package]
name = "hunter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hunter"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.7", features = ["derive"] }
tokio = { version = "1.8.0", features = ["macros", "rt-multi-thread"] }
rayon = "1.5"
tempfile = "3.8.1"

# switch to git dependency
noirc_frontend = { path = "../../noir_dev/noir/compiler/noirc_frontend" }
noirc_errors = { path = "../../noir_dev/noir/compiler/noirc_errors"}

# noirc_frontend = { path = "../../../../../..//Users/furnic/dev/noir_dev/noir/compiler/noirc_frontend" }
# noirc_errors = { path = "../../../../../..//Users/furnic/dev/noir_dev/noir/compiler/noirc_errors"}
