[package]
name = "hunter"
version = "1.0.0"
edition = "2021"
authors = ["Nick Furfaro <furnic@skiff.com>"]

[[bin]]
name = "hunter"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
colored = "2.0.4"
indicatif = {version = "*", features = ["rayon"]}
prettytable-rs = "^0.10"
rayon = "1.5"
regex = "1.10.2"
sled = "0.34.7"
tempdir = "0.3.7"
tempfile = "3.8.1"
tokio = { version = "1.8.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.8"
