[package]
name = "hunter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hunter"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.7", features = ["derive"] }
noirc_frontend = { path = "../../../../../../home/furnic/Dev/noir_dev/noir/compiler/noirc_frontend" }
tokio = { version = "1.8.0", features = ["macros", "rt-multi-thread"] }
