[package]
name = "hunter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.7", features = ["derive"] }
noirc_frontend = { path = "/home/furnic/Dev/noir_dev/noir/compiler/noirc_frontend" }