
sequenceDiagram
    actor User
    User->>Cli: Mutate! (Args & Opts)
    Cli->>Core: Run (with config)
    Core->>Src: Find .nr files
    Src-->Core: Here you go
    Core->>Copies: Make copies
    Core->>Mutator: Mutate Tokens
    Mutator->>Copies: Fetch Copies
    Copies-->Mutator: copies




